package greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import greendao.Food_groupDao;
import greendao.Food_descDao;
import greendao.KeywordsDao;
import greendao.Food_keywordsDao;
import greendao.Nutr_defDao;
import greendao.Nutr_dataDao;
import greendao.WeightDao;
import greendao.User_entryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        Food_groupDao.createTable(db, ifNotExists);
        Food_descDao.createTable(db, ifNotExists);
        KeywordsDao.createTable(db, ifNotExists);
        Food_keywordsDao.createTable(db, ifNotExists);
        Nutr_defDao.createTable(db, ifNotExists);
        Nutr_dataDao.createTable(db, ifNotExists);
        WeightDao.createTable(db, ifNotExists);
        User_entryDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        Food_groupDao.dropTable(db, ifExists);
        Food_descDao.dropTable(db, ifExists);
        KeywordsDao.dropTable(db, ifExists);
        Food_keywordsDao.dropTable(db, ifExists);
        Nutr_defDao.dropTable(db, ifExists);
        Nutr_dataDao.dropTable(db, ifExists);
        WeightDao.dropTable(db, ifExists);
        User_entryDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(Food_groupDao.class);
        registerDaoClass(Food_descDao.class);
        registerDaoClass(KeywordsDao.class);
        registerDaoClass(Food_keywordsDao.class);
        registerDaoClass(Nutr_defDao.class);
        registerDaoClass(Nutr_dataDao.class);
        registerDaoClass(WeightDao.class);
        registerDaoClass(User_entryDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
