package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Food_group;
import greendao.Food_desc;
import greendao.Keywords;
import greendao.Food_keywords;
import greendao.Nutr_def;
import greendao.Nutr_data;
import greendao.Weight;
import greendao.User_entry;

import greendao.Food_groupDao;
import greendao.Food_descDao;
import greendao.KeywordsDao;
import greendao.Food_keywordsDao;
import greendao.Nutr_defDao;
import greendao.Nutr_dataDao;
import greendao.WeightDao;
import greendao.User_entryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig food_groupDaoConfig;
    private final DaoConfig food_descDaoConfig;
    private final DaoConfig keywordsDaoConfig;
    private final DaoConfig food_keywordsDaoConfig;
    private final DaoConfig nutr_defDaoConfig;
    private final DaoConfig nutr_dataDaoConfig;
    private final DaoConfig weightDaoConfig;
    private final DaoConfig user_entryDaoConfig;

    private final Food_groupDao food_groupDao;
    private final Food_descDao food_descDao;
    private final KeywordsDao keywordsDao;
    private final Food_keywordsDao food_keywordsDao;
    private final Nutr_defDao nutr_defDao;
    private final Nutr_dataDao nutr_dataDao;
    private final WeightDao weightDao;
    private final User_entryDao user_entryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        food_groupDaoConfig = daoConfigMap.get(Food_groupDao.class).clone();
        food_groupDaoConfig.initIdentityScope(type);

        food_descDaoConfig = daoConfigMap.get(Food_descDao.class).clone();
        food_descDaoConfig.initIdentityScope(type);

        keywordsDaoConfig = daoConfigMap.get(KeywordsDao.class).clone();
        keywordsDaoConfig.initIdentityScope(type);

        food_keywordsDaoConfig = daoConfigMap.get(Food_keywordsDao.class).clone();
        food_keywordsDaoConfig.initIdentityScope(type);

        nutr_defDaoConfig = daoConfigMap.get(Nutr_defDao.class).clone();
        nutr_defDaoConfig.initIdentityScope(type);

        nutr_dataDaoConfig = daoConfigMap.get(Nutr_dataDao.class).clone();
        nutr_dataDaoConfig.initIdentityScope(type);

        weightDaoConfig = daoConfigMap.get(WeightDao.class).clone();
        weightDaoConfig.initIdentityScope(type);

        user_entryDaoConfig = daoConfigMap.get(User_entryDao.class).clone();
        user_entryDaoConfig.initIdentityScope(type);

        food_groupDao = new Food_groupDao(food_groupDaoConfig, this);
        food_descDao = new Food_descDao(food_descDaoConfig, this);
        keywordsDao = new KeywordsDao(keywordsDaoConfig, this);
        food_keywordsDao = new Food_keywordsDao(food_keywordsDaoConfig, this);
        nutr_defDao = new Nutr_defDao(nutr_defDaoConfig, this);
        nutr_dataDao = new Nutr_dataDao(nutr_dataDaoConfig, this);
        weightDao = new WeightDao(weightDaoConfig, this);
        user_entryDao = new User_entryDao(user_entryDaoConfig, this);

        registerDao(Food_group.class, food_groupDao);
        registerDao(Food_desc.class, food_descDao);
        registerDao(Keywords.class, keywordsDao);
        registerDao(Food_keywords.class, food_keywordsDao);
        registerDao(Nutr_def.class, nutr_defDao);
        registerDao(Nutr_data.class, nutr_dataDao);
        registerDao(Weight.class, weightDao);
        registerDao(User_entry.class, user_entryDao);
    }
    
    public void clear() {
        food_groupDaoConfig.getIdentityScope().clear();
        food_descDaoConfig.getIdentityScope().clear();
        keywordsDaoConfig.getIdentityScope().clear();
        food_keywordsDaoConfig.getIdentityScope().clear();
        nutr_defDaoConfig.getIdentityScope().clear();
        nutr_dataDaoConfig.getIdentityScope().clear();
        weightDaoConfig.getIdentityScope().clear();
        user_entryDaoConfig.getIdentityScope().clear();
    }

    public Food_groupDao getFood_groupDao() {
        return food_groupDao;
    }

    public Food_descDao getFood_descDao() {
        return food_descDao;
    }

    public KeywordsDao getKeywordsDao() {
        return keywordsDao;
    }

    public Food_keywordsDao getFood_keywordsDao() {
        return food_keywordsDao;
    }

    public Nutr_defDao getNutr_defDao() {
        return nutr_defDao;
    }

    public Nutr_dataDao getNutr_dataDao() {
        return nutr_dataDao;
    }

    public WeightDao getWeightDao() {
        return weightDao;
    }

    public User_entryDao getUser_entryDao() {
        return user_entryDao;
    }

}
