package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Food_keywords;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOOD_KEYWORDS.
*/
public class Food_keywordsDao extends AbstractDao<Food_keywords, Void> {

    public static final String TABLENAME = "FOOD_KEYWORDS";

    /**
     * Properties of entity Food_keywords.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property NDB_no = new Property(0, Long.class, "NDB_no", false, "NDB_NO");
        public final static Property Lang_no = new Property(1, Long.class, "Lang_no", false, "LANG_NO");
    };

    private DaoSession daoSession;


    public Food_keywordsDao(DaoConfig config) {
        super(config);
    }
    
    public Food_keywordsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOOD_KEYWORDS' (" + //
                "'NDB_NO' INTEGER," + // 0: NDB_no
                "'LANG_NO' INTEGER);"); // 1: Lang_no
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOOD_KEYWORDS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Food_keywords entity) {
        stmt.clearBindings();
 
        Long NDB_no = entity.getNDB_no();
        if (NDB_no != null) {
            stmt.bindLong(1, NDB_no);
        }
 
        Long Lang_no = entity.getLang_no();
        if (Lang_no != null) {
            stmt.bindLong(2, Lang_no);
        }
    }

    @Override
    protected void attachEntity(Food_keywords entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Food_keywords readEntity(Cursor cursor, int offset) {
        Food_keywords entity = new Food_keywords( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // NDB_no
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1) // Lang_no
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Food_keywords entity, int offset) {
        entity.setNDB_no(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLang_no(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Food_keywords entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Food_keywords entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFood_descDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getKeywordsDao().getAllColumns());
            builder.append(" FROM FOOD_KEYWORDS T");
            builder.append(" LEFT JOIN FOOD_DESC T0 ON T.'NDB_NO'=T0.'NDB_NO'");
            builder.append(" LEFT JOIN KEYWORDS T1 ON T.'LANG_NO'=T1.'LANG_NO'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Food_keywords loadCurrentDeep(Cursor cursor, boolean lock) {
        Food_keywords entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Food_desc food_desc = loadCurrentOther(daoSession.getFood_descDao(), cursor, offset);
        entity.setFood_desc(food_desc);
        offset += daoSession.getFood_descDao().getAllColumns().length;

        Keywords keywords = loadCurrentOther(daoSession.getKeywordsDao(), cursor, offset);
        entity.setKeywords(keywords);

        return entity;    
    }

    public Food_keywords loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Food_keywords> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Food_keywords> list = new ArrayList<Food_keywords>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Food_keywords> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Food_keywords> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
