package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FOOD_GROUP.
 */
public class Food_group {

    private Long Fdgrp_no;
    private String name;

    public Food_group() {
    }

    public Food_group(Long Fdgrp_no) {
        this.Fdgrp_no = Fdgrp_no;
    }

    public Food_group(Long Fdgrp_no, String name) {
        this.Fdgrp_no = Fdgrp_no;
        this.name = name;
    }

    public Long getFdgrp_no() {
        return Fdgrp_no;
    }

    public void setFdgrp_no(Long Fdgrp_no) {
        this.Fdgrp_no = Fdgrp_no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
