package greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Food_desc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table FOOD_DESC.
*/
public class Food_descDao extends AbstractDao<Food_desc, Long> {

    public static final String TABLENAME = "FOOD_DESC";

    /**
     * Properties of entity Food_desc.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property NDB_no = new Property(0, Long.class, "NDB_no", true, "NDB_NO");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Fdgrp_no = new Property(2, Long.class, "Fdgrp_no", false, "FDGRP_NO");
    };

    private DaoSession daoSession;


    public Food_descDao(DaoConfig config) {
        super(config);
    }
    
    public Food_descDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'FOOD_DESC' (" + //
                "'NDB_NO' INTEGER PRIMARY KEY ," + // 0: NDB_no
                "'NAME' TEXT," + // 1: name
                "'FDGRP_NO' INTEGER);"); // 2: Fdgrp_no
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'FOOD_DESC'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Food_desc entity) {
        stmt.clearBindings();
 
        Long NDB_no = entity.getNDB_no();
        if (NDB_no != null) {
            stmt.bindLong(1, NDB_no);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Long Fdgrp_no = entity.getFdgrp_no();
        if (Fdgrp_no != null) {
            stmt.bindLong(3, Fdgrp_no);
        }
    }

    @Override
    protected void attachEntity(Food_desc entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Food_desc readEntity(Cursor cursor, int offset) {
        Food_desc entity = new Food_desc( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // NDB_no
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // Fdgrp_no
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Food_desc entity, int offset) {
        entity.setNDB_no(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFdgrp_no(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Food_desc entity, long rowId) {
        entity.setNDB_no(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Food_desc entity) {
        if(entity != null) {
            return entity.getNDB_no();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getFood_groupDao().getAllColumns());
            builder.append(" FROM FOOD_DESC T");
            builder.append(" LEFT JOIN FOOD_GROUP T0 ON T.'FDGRP_NO'=T0.'FDGRP_NO'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Food_desc loadCurrentDeep(Cursor cursor, boolean lock) {
        Food_desc entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Food_group food_group = loadCurrentOther(daoSession.getFood_groupDao(), cursor, offset);
        entity.setFood_group(food_group);

        return entity;    
    }

    public Food_desc loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Food_desc> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Food_desc> list = new ArrayList<Food_desc>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Food_desc> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Food_desc> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
