package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NUTR_DEF.
 */
public class Nutr_def {

    private Long Nutr_no;
    private String units;
    private String name;

    public Nutr_def() {
    }

    public Nutr_def(Long Nutr_no) {
        this.Nutr_no = Nutr_no;
    }

    public Nutr_def(Long Nutr_no, String units, String name) {
        this.Nutr_no = Nutr_no;
        this.units = units;
        this.name = name;
    }

    public Long getNutr_no() {
        return Nutr_no;
    }

    public void setNutr_no(Long Nutr_no) {
        this.Nutr_no = Nutr_no;
    }

    public String getUnits() {
        return units;
    }

    public void setUnits(String units) {
        this.units = units;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
